version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@3.1.5

commands:
  install_node_modules:
    description: 'Install node modules'
    steps:
      - restore_cache:
          name: Restore npm Package Cache
          keys:
            - npm-packages-{{ checksum "npm-lock.yaml" }}
      - run:
          name: Install npm package manager
          command: |
            sudo corepack enable
            sudo corepack prepare npm@latest-8 --activate
      - run:
          name: Install Dependencies
          command: |
            npm install
      - save_cache:
          name: Save npm Package Cache
          key: npm-packages-{{ checksum "npm-lock.yaml" }}
          paths:
            - node_modules

jobs:
  build:
    executor:
      name: node/default
      tag: '16.18.0'
    steps:
      - checkout
      - install_node_modules
      - run:
          name: Lint and Test
          command: npm run pre-commit

  deploy:
    executor:
      name: node/default
      tag: '16.18.0'
    steps:
      - checkout
      - install_node_modules
      - aws-cli/setup
      - run:
          name: 'Install aws-amplify CLI'
          command: |
            sudo npm install -g @aws-amplify/cli --unsafe-perm=true
      - run:
          name: 'Show AWS CLI and Amplify Versions'
          command: |
            aws --version
            amplify --version
      - run:
          name: Checkout Amplify
          command: |
            amplify init --amplify "{\"envName\"😕"$VITE_NODE_ENV\"}" --providers "{\"awscloudformation\":{\"useProfile\":true,\"profileName\"😕"default\"}}" --yes
      - run:
          name: Deploy
          command: |
            amplify publish --invalidateCloudFront --codegen "{\"generateCode\":false}" --yes

workflows:
  build-and-deploy-staging:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
          context: xfactor-staging